#alias gvim='/home/josh/.gvim'
#alias R='R_LIBS_USER=/home/josh/R/library /usr/bin/R --no-save'
alias Rscript='R_LIBS_USER=/home/josh/R/library /usr/bin/Rscript'
#alias Rd='R_LIBS_USER='\''/home/josh/R/library-dev:/home/josh/R/library'\'' /usr/bin/R --no-save'
alias cd2='cd ../..'
alias Rdevel='~/R/R-build/bin/R'
alias xts-rforge='cd ~/R/packages/xts/pkg'
alias xts='cd ~/git/xts'
alias zoo='cd ~/R/packages/zoo/pkg'
alias ttr-rforge='cd ~/R/packages/TTR'
alias ttr='cd ~/git/TTR'
alias blotter='cd ~/git/blotter'
alias quantstrat='cd ~/git/quantstrat'
alias deoptim='cd ~/R/packages/deoptim/pkg'
alias lspm-rforge='cd ~/R/packages/lspm'
alias lspm='cd ~/git/LSPM'
alias quantmod-rforge='cd ~/R/packages/quantmod'
alias quantmod='cd ~/git/quantmod'

